In [10]:
pip install kafka-python

Requirement already satisfied: kafka-python in C:\Users\User\anaconda3\Lib\site-packages (3.0.10)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd
from kafka import KafkaProducer
from time import sleep
from json import dumps
import json

In [16]:
producer = KafkaProducer(bootstrap_servers=['15.240.164.146:9092'],
                         value_serializer=lambda x: 
                         dumps(x).encode('utf-8'))

In [5]:
producer.send('demo', value={'Data':'Engineer'})

In [17]:
df = pd.read_csv("indexProcessed.csv")
df.head()

,Index,Date,Open,High,Low,Close,Adj Close,Volume,CloseUSD
0,HSI,1986-12-31,2568.300049,2568.300049,2568.300049,2568.300049,2568.300049,0.0,333.879006
1,HSI,1987-01-02,2540.100098,2540.100098,2540.100098,2540.100098,2540.100098,0.0,330.213013
2,HSI,1987-01-05,2552.399902,2552.399902,2552.399902,2552.399902,2552.399902,0.0,331.811987
3,HSI,1987-01-06,2583.899902,2583.899902,2583.899902,2583.899902,2583.899902,0.0,335.906987
4,HSI,1987-01-07,2607.100098,2607.100098,2607.100098,2607.100098,2607.100098,0.0,338.923013

In [18]:
df.sample(1)

,Index,Date,Open,High,Low,Close,Adj Close,Volume,CloseUSD
33249,IXIC,2013-12-10,4061.169922,4074.01001,4056.48999,4060.48999,4060.48999,1.864860e+09,4060.48999

In [ ]:
while True:
    dict_stock = df.sample(1).to_dict(orient="records")[0]
    producer.send('demo', value=dict_stock)
    sleep(1)